### PR TITLE
Comp fix

### PR DESCRIPTION
**Pull request by okawo80085**
now it's a full fledged steamvr driver

### CODE REVIEW

**Comment by MaxonYT** [comment]
изображение

**Comment by HagimaNagima** [comment]
https://media.discordapp.net/attachments/368000955578580993/776792659913605141/image0-4.gif

**Comment by SlarkPro99** [comment]
BpeM9I_MoJIoTa

**Comment by HagimaNagima** [comment]
image

**Comment by Teqptel** [comment]
785d1f3978c56227e3939caf82bc0502

**Pull request merged**
